### ISSUE TITLE
ubuntu 22.04 cnf and i386

### ISSUE THREAD

**Issue by jumpingmushroom** [ich777/docker-ubuntu-mirror#1]
Hi!

First of all, thanks for a great initiative to enable ubuntu local repos on unraid. As a person with a monthly quota on bandwidth and a collection of ubuntu servers at home, this helps a lot to keep downloads from the Internet limited.

I did however stumble upon a couple of issues with your image. First off there is apparently an issue with apt-mirror itself ref https://github.com/apt-mirror/apt-mirror/issues/145 where apt-mirror does not take into account the cnf (command not found) metadata. This can be found here http://archive.ubuntu.com/ubuntu/dists/jammy/main/cnf/ . My "solution" as I could not modify the apt-mirror script was to simply remove /etc/apt/apt.conf.d/50command-not-found, so that the metadata is no longer requested. Also I don't really need to know what package contains commands, so It's fine.

I also noticed that i386 is not downloaded, so I simply removed i386 from my arch i dpkg (dpkg --remove-architecture i386) as I have no use for 32-bit binaries. I didn't investigate further why this is not downloaded, but it should probably be investigated further.

I know these things might not be something you can affect directly, as it seems the apt-mirror project is more or less abandoned, but I just thought I'd give you a heads-up.

**Comment by ich777** [comment]
Thank you for the report.

TBH I have only tested the `restricted` repository because I don't use Ubuntu whatsoever (got too much issues with it in the past with Docker containers and I'm a Debian guy anyways... :D ) I also did the container on request from a user on the Unraid forums.

> First off there is apparently an issue with apt-mirror itself ref [apt-mirror/apt-mirror#145](https://github.com/apt-mirror/apt-mirror/issues/145) where apt-mirror does not take into account the cnf (command not found) metadata. This can be found here http://archive.ubuntu.com/ubuntu/dists/jammy/main/cnf/ .

Can you describe and/or post a screenshot what is happening exactly so that I can reproduce it? Which repos do I have to mirror to reproduce this?

> My "solution" as I could not modify the apt-mirror script was to simply remove /etc/apt/apt.conf.d/50command-not-found

This can be also done in my container if the file exists with a `user.sh` file.
Simply create a file on the host (Unraid) named `user.sh` (somewhere where it persists like in `appdata`) and mount it in the template to the file with the host path eg: `/mnt/user/appdata/scripts/user.sh` and in the container you have to mount it to this specific path: `/opt/scripts/user.sh`
The file should have the contents:
```
#!/bin/bash
if [ -f /etc/apt/apt.conf.d/50command-not-found ]; then
  rm -f /etc/apt/apt.conf.d/50command-not-found
fi
```
With this you ensure that the file you mentioned above is removed before the `apt-mirror` even starts.

> I also noticed that i386 is not downloaded, so I simply removed i386 from my arch i dpkg (dpkg --remove-architecture i386) as I have no use for 32-bit binaries. I didn't investigate further why this is not downloaded, but it should probably be investigated further.

You should be able to download i386 by simply adding this line to your mirror.list if I'm not mistaken:
`deb-i386 http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse`

If someone wants to really mirror i386 they will figure it out eventually or read the documentation on apt-mirror on the Ubuntu Wiki where it is also described.



> I know these things might not be something you can affect directly, as it seems the apt-mirror project is more or less abandoned, but I just thought I'd give you a heads-up.

Are you really sure that is abandoned? I don't think so but I could be wrong about that.

Anyways, I hope this helps.

**Comment by ich777** [comment]
@jumpingmushroom does the above answer resolve your issues?

**Comment by ich777** [comment]
Closing due to no response, feel free to open the issue again if you have further questions or create a new one @jumpingmushroom.
